apiVersion: v1
kind: Pod
metadata:
  name: my-init-pod-hostpath
  labels:
    app: my-init-pod-hostpath
spec:
  containers:
  - name: my-container
    image: redis
    volumeMounts:
    - mountPath: /mnt/hi
      name: cache-volume
  initContainers:
  - name: my-init-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo -n "hello" > /mnt/hi/info']
    volumeMounts:
    - mountPath: /mnt/hi
      name: cache-volume
  volumes:
  - name: cache-volume
    hostPath:
      path: /data
      type: DirectoryOrCreate

    