apiVersion: v1
kind: Pod
metadata:
  name: busy-sleeper
  labels:
    env: test
spec:
  containers:
  - name: busybox-1
    image: busybox
    args: ["sleep", "100000"]
  - name: busybox-2
    image: busybox
    args: ["sleep", "100000"]
  - name: busybox-3
    image: busybox
    args: ["sleep", "100000"]
  - name: busybox-4
    image: busybox
    args: ["sleep", "100000"]
  nodeSelector:
    Status: VIP