apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cka1
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
  namespace: cka1
spec:
  containers:
  - image: nginx:1.16.0
    name: web
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
