apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: test
  name: busy
spec:
  containers:
  - image: busybox
    name: busy-1
    args:
     - sleep
     - "3000"
  - image: busybox
    name: busy-2
    command: ["sh", "-c", "sleep 3000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}