apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: cache
  name: cache
spec:
  replicas: 3
  selector:
    matchLabels:
      run: cache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cache
    spec:
      containers:
      - image: memcached
        name: cache
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: cache
  name: cache
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: 11211
  selector:
    run: cache
  type: NodePort
status:
  loadBalancer: {}