apiVersion: v1
kind: Pod
metadata:
  name: my-cache
  labels:
    app: my-cache
spec:
  containers:
  - name: my-cache
    image: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: lookup-pod
  labels:
    app: lookup-pod
spec:
  containers:
  - name: lookup-pod
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 10000']