apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: limited-hog
  name: limited-hog
  namespace:  low-usage-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limited-hog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: limited-hog
    spec:
      containers:
      - image: vish/stress
        imagePullPolicy: Always
        name: stress
        resources: {}
status: {}
