apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mypv-deployment
  name: mypv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mypv-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mypv-deployment
    spec:
      containers:
      - image: nginx
        name: mypv-deployment
        resources: {}
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: task-pv-storage 
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: pvc-one
status: {}