apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        root /usr/share/nginx/html;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  securityContext:
    runAsUser: 4242
    runAsGroup: 4242
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: cachevol
      mountPath: /var/cache/nginx
    - name: cfgvol
      mountPath: /etc/nginx/conf.d
    - name: runvol
      mountPath: /var/run
  volumes:
  - name: cachevol
    emptyDir: {}
  - name: runvol
    emptyDir: {}
  - name: cfgvol
    configMap:
      name: nginx-conf

