apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myuserpod
  name: myuserpod
spec:
  securityContext:
    runAsUser: 4242
    runAsGroup: 4242
  containers:
  - image: busybox
    name: myuserpod
    command: ['sh', '-c', 'sleep 10000']
