apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sleeper-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sleeper
            image: busybox
            command: ["sleep"]
            args: ["3"]
          restartPolicy: Never
      backoffLimit: 3
      completions: 2
      parallelism: 2