apiVersion: v1
kind: Service
metadata:
  labels:
    run: my1stdeployment
  name: my1stdeployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: my1stdeployment