version: "3.3"
services:    
  elasticsearch:
    image: elasticsearch:6.4.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: kibana:6.4.2
    ports:
      - "5601:5601"

volumes:
  esdata:

