apiVersion: batch/v1
kind: Job
metadata:
  name: sleeper-job
spec:
  template:
    spec:
      containers:
      - name: sleeper
        image: busybox
        command: ["sleep"]
        args: ["3"]
      restartPolicy: Never
  backoffLimit: 3
  completions: 2
  parallelism: 2
  