apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: nginx-ds
  name: nginx-ds
spec:
  selector:
    matchLabels:
      name: nginx-ds
  template:
    metadata:
      labels:
        name: nginx-ds
    spec:
      containers:
      - image: image
        name: image-ds
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi