apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: website
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      run: website
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: website
    spec:
      containers:
      - image: nginx
        name: website
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cache-volume
      initContainer:
      - name: init-site
        image: busybox:1.28
        command: ['sh', '-c', 'echo $HOSTNAME > /mnt/index.html']
        volumeMounts:
        - mountPath: /mnt
          name: cache-volume
      volumes:
      - name: cahce-volume
          emptyDir: {}