---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: probed-pod
  labels:
    app: probed-pod
    task: crashloopbackoff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probed-pod
      task: crashloopbackoff
  template:
    metadata:
      labels:
        app: probed-pod
        task: crashloopbackoff
    spec:
      containers:
      - name: probed-pod
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 1
      volumes:
      - name: config
        configMap:
          name: nginx-conf

