apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # health endpoint for kubernetes
        location /healthz {
            access_log off;
            return 200 "healthy\n";
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-conf

