apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: cncf
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cka1
  name: cka1
  namespace: cncf
spec:
  containers:
  - image: nginx:1.16.0
    name: cka1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
