apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: cache
  name: cache
spec:
  replicas: 5
  selector:
    matchLabels:
      run: cache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cache
    spec:
      containers:
      - image: memcached
        name: cache
        resources: {}
status: {}
