apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: cka3
  name: cka3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: cka3
  type: NodePort
status:
  loadBalancer: {}
