---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: q6-pod
  name: q6-pod
spec:
  containers:
  - image: nginx
    name: q6-pod
    resources: {}
    volumeMounts:
      - mountPath: /tmp/secret-volume
        name: secret-vol
  volumes:
  - name: secret-vol
    secret:
      secretName: mymisssecret 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
