apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    role: webserver
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      role: webserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        role: webserver
    spec:
      containers:
      - image: nginx
        name: nginx-deploy
        ports:
        - containerPort: 80
        resources: {}
status: {}
