apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmap-pod2
  name: configmap-pod2
spec:
  containers:
  - image: nginx
    name: configmap-pod2
    envFrom:
    - configMapRef:
        name: colours