apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: configmap-pod
  name: configmap-pod
spec:
  containers:
  - image: nginx
    name: configmap-pod
    env:
      - name: ilike
        valueFrom:
          configMapKeyRef:
            name: colours
            key: favorite
