apiVersion: v1
kind: Pod
metadata:
  name: my-secret-file-pod
spec:
  containers:
  - name: my-secret-container
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: my-secret
